export const booklist = [
    {
        "_id": "67f06b40cdd5f79c66493ff5",
        "id": "1442",
        "name": "21 Types of SQL Join",
        "title": "Advanced ANSI SQL Data Modeling and Structure Processing",
        "cover": "https://books.google.com/books/content?id=6aMJH43GwpIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Artech House",
        "author": "Michael M. David",
        "summary": "This new book is an essential tool for utilizing the ANSI SQL outer join operation, and an indispensable guide to using this operation to perform simple or complex data modeling. It provides a comprehensive look at the outer join operation, its powerful syntax, and new features and capabilities that can be developed based on the operation's data modeling capacity.",
        "previewLink": "No preview link",
        "isbn_13": "9781580530385",
        "original_path": "https://aibookshub.github.io/b1442/1442/21 Types of SQL Join.pdf"
    },
    {
        "_id": "67f06b41cdd5f79c66493ff6",
        "id": "1442",
        "name": "26 Pages Pandas",
        "title": "Pandas",
        "cover": "https://books.google.com/books/content?id=05ivSsL4EpIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Gareth Stevens Publishing LLLP",
        "author": "Susan Kueffner",
        "summary": "Describes the physical characteristics, habitat, and behavior of pandas.",
        "previewLink": "No preview link",
        "isbn_13": "9780836891003",
        "original_path": "https://aibookshub.github.io/b1442/1442/26 Pages Pandas.pdf"
    },
    {
        "_id": "67f06b42cdd5f79c66493ff7",
        "id": "1442",
        "name": "Ace the Programming Interview - 160 Questions and Answers for Success",
        "title": "Ace the Programming Interview",
        "cover": "https://books.google.com/books/content?id=DEn71rgH4_4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "Edward Guiness",
        "summary": "Be prepared to answer the most relevant interview questions and land the job Programmers are in demand, but to land the job, you must demonstrate knowledge of those things expected by today's employers. This guide sets you up for success. Not only does it provide 160 of the most commonly asked interview questions and model answers, but it also offers insight into the context and motivation of hiring managers in today's marketplace. Written by a veteran hiring manager, this book is a comprehensive guide for experienced and first-time programmers alike. Provides insight into what drives the recruitment process and how hiring managers think Covers both practical knowledge and recommendations for handling the interview process Features 160 actual interview questions, including some related to code samples that are available for download on a companion website Includes information on landing an interview, preparing a cheat-sheet for a phone interview, how to demonstrate your programming wis",
        "previewLink": "No preview link",
        "isbn_13": "9781118518564",
        "original_path": "https://aibookshub.github.io/b1442/1442/Ace the Programming Interview - 160 Questions and Answers for Success.pdf"
    },
    {
        "_id": "67f06b42cdd5f79c66493ff8",
        "id": "1442",
        "name": "Addison.Wesley.-.The.Pragmatic.Programmer.1ed.1999.程序员修炼之道",
        "title": "代码大全",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Unknown Author",
        "summary": "软件构建之实践指南",
        "previewLink": "No preview link",
        "isbn_13": "9787121046186",
        "original_path": "https://aibookshub.github.io/b1442/1442/Addison.Wesley.-.The.Pragmatic.Programmer.1ed.1999.程序员修炼之道.pdf"
    },
    {
        "_id": "67f06b43cdd5f79c66493ff9",
        "id": "1442",
        "name": "Clean Code Handbook - LeetCode 50 Common Interview Questions",
        "title": "Elements of Programming Interviews",
        "cover": "https://books.google.com/books/content?id=y6FLBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "EPI",
        "author": "Adnan Aziz",
        "summary": "The core of EPI is a collection of over 300 problems with detailed solutions, including 100 figures, 250 tested programs, and 150 variants. The problems are representative of questions asked at the leading software companies. The book begins with a summary of the nontechnical aspects of interviewing, such as common mistakes, strategies for a great interview, perspectives from the other side of the table, tips on negotiating the best offer, and a guide to the best ways to use EPI. The technical core of EPI is a sequence of chapters on basic and advanced data structures, searching, sorting, broad algorithmic principles, concurrency, and system design. Each chapter consists of a brief review, followed by a broad and thought-provoking series of problems. We include a summary of data structure, algorithm, and problem solving patterns.",
        "previewLink": "No preview link",
        "isbn_13": "9781479274833",
        "original_path": "https://aibookshub.github.io/b1442/1442/Clean Code Handbook - LeetCode 50 Common Interview Questions.pdf"
    },
    {
        "_id": "67f06b44cdd5f79c66493ffa",
        "id": "1442",
        "name": "Coding Interviews - Questions, Analysis & Solutions",
        "title": "Coding Interviews",
        "cover": "https://books.google.com/books/content?id=p4UcrLAYzd4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Apress",
        "author": "Harry He",
        "summary": "This book is about coding interview questions from software and Internet companies. It covers five key factors which determine performance of candidates: (1) the basics of programming languages, data structures and algorithms, (2) approaches to writing code with high quality, (3) tips to solve difficult problems, (4) methods to optimize code, (5) soft skills required in interviews. The basics of languages, algorithms and data structures are discussed as well as questions that explore how to write robust solutions after breaking down problems into manageable pieces. It also includes examples to focus on modeling and creative problem solving. Interview questions from the most popular companies in the IT industry are taken as examples to illustrate the five factors above. Besides solutions, it contains detailed analysis, how interviewers evaluate solutions, as well as why they like or dislike them. The author makes clever use of the fact that interviewees will have limited time to program",
        "previewLink": "No preview link",
        "isbn_13": "9781430247623",
        "original_path": "https://aibookshub.github.io/b1442/1442/Coding Interviews - Questions, Analysis & Solutions.pdf"
    },
    {
        "_id": "67f06b44cdd5f79c66493ffb",
        "id": "1442",
        "name": "Cracking the Coding Interview - 150 Programming Interview Questions and Solutions 4e Small",
        "title": "Cracking the Coding Interview",
        "cover": "https://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking the Coding Interview - 150 Programming Interview Questions and Solutions 4e Small.pdf"
    },
    {
        "_id": "67f06b45cdd5f79c66493ffc",
        "id": "1442",
        "name": "Cracking the Coding Interview, 4 Edition - 150 Programming Interview Questions and Solutions",
        "title": "Cracking the Coding Interview",
        "cover": "https://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking the Coding Interview, 4 Edition - 150 Programming Interview Questions and Solutions.pdf"
    },
    {
        "_id": "67f06b46cdd5f79c66493ffd",
        "id": "1442",
        "name": "Cracking the Coding Interview, 6th Edition",
        "title": "Cracking the Coding Interview",
        "cover": "https://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking the Coding Interview, 6th Edition.pdf"
    },
    {
        "_id": "67f06b46cdd5f79c66493ffe",
        "id": "1442",
        "name": "Cracking_the_Coding_Interview_6th_Edition_189_Programming_Questions",
        "title": "Cracking the Coding Interview",
        "cover": "https://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking_the_Coding_Interview_6th_Edition_189_Programming_Questions.pdf"
    },
    {
        "_id": "67f06b47cdd5f79c66493fff",
        "id": "1442",
        "name": "Data Cleaning Guidelines",
        "title": "Best Practices in Data Cleaning",
        "cover": "https://books.google.com/books/content?id=G8V1AwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "SAGE Publications",
        "author": "Jason W. Osborne",
        "summary": "Many researchers jump from data collection directly into testing hypothesis without realizing these tests can go profoundly wrong without clean data. This book provides a clear, accessible, step-by-step process of important best practices in preparing for data collection, testing assumptions, and examining and cleaning data in order to decrease error rates and increase both the power and replicability of results. Jason W. Osborne, author of the handbook Best Practices in Quantitative Methods (SAGE, 2008) provides easily-implemented suggestions that are evidence-based and will motivate change in practice by empirically demonstrating—for each topic—the benefits of following best practices and the potential consequences of not following these guidelines.",
        "previewLink": "No preview link",
        "isbn_13": "9781452281049",
        "original_path": "https://aibookshub.github.io/b1442/1442/Data Cleaning Guidelines.pdf"
    },
    {
        "_id": "67f06b48cdd5f79c66494000",
        "id": "1442",
        "name": "Data Cleaning",
        "title": "Best Practices in Data Cleaning",
        "cover": "https://books.google.com/books/content?id=G8V1AwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "SAGE Publications",
        "author": "Jason W. Osborne",
        "summary": "Many researchers jump from data collection directly into testing hypothesis without realizing these tests can go profoundly wrong without clean data. This book provides a clear, accessible, step-by-step process of important best practices in preparing for data collection, testing assumptions, and examining and cleaning data in order to decrease error rates and increase both the power and replicability of results. Jason W. Osborne, author of the handbook Best Practices in Quantitative Methods (SAGE, 2008) provides easily-implemented suggestions that are evidence-based and will motivate change in practice by empirically demonstrating—for each topic—the benefits of following best practices and the potential consequences of not following these guidelines.",
        "previewLink": "No preview link",
        "isbn_13": "9781452281049",
        "original_path": "https://aibookshub.github.io/b1442/1442/Data Cleaning.pdf"
    },
    {
        "_id": "67f06b49cdd5f79c66494001",
        "id": "1442",
        "name": "Data_Science_Interview_Prep_for_SQL,_Panda,_Python",
        "title": "Build a Career in Data Science",
        "cover": "https://books.google.com/books/content?id=4dDVDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Manning",
        "author": "Emily Robinson",
        "summary": "Summary You are going to need more than technical knowledge to succeed as a data scientist. Build a Career in Data Science teaches you what school leaves out, from how to land your first job to the lifecycle of a data science project, and even how to become a manager. Purchase of the print book includes a free eBook in PDF, Kindle, and ePub formats from Manning Publications. About the technology What are the keys to a data scientist’s long-term success? Blending your technical know-how with the right “soft skills” turns out to be a central ingredient of a rewarding career. About the book Build a Career in Data Science is your guide to landing your first data science job and developing into a valued senior employee. By following clear and simple instructions, you’ll learn to craft an amazing resume and ace your interviews. In this demanding, rapidly changing field, it can be challenging to keep projects on track, adapt to company needs, and manage tricky stakeholders. You’ll love the in",
        "previewLink": "No preview link",
        "isbn_13": "9781617296246",
        "original_path": "https://aibookshub.github.io/b1442/1442/Data_Science_Interview_Prep_for_SQL,_Panda,_Python.pdf"
    },
    {
        "_id": "67f06b49cdd5f79c66494002",
        "id": "1442",
        "name": "Elements of Programming Interviews",
        "title": "Elements of Programming Interviews",
        "cover": "https://books.google.com/books/content?id=y6FLBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "EPI",
        "author": "Adnan Aziz",
        "summary": "The core of EPI is a collection of over 300 problems with detailed solutions, including 100 figures, 250 tested programs, and 150 variants. The problems are representative of questions asked at the leading software companies. The book begins with a summary of the nontechnical aspects of interviewing, such as common mistakes, strategies for a great interview, perspectives from the other side of the table, tips on negotiating the best offer, and a guide to the best ways to use EPI. The technical core of EPI is a sequence of chapters on basic and advanced data structures, searching, sorting, broad algorithmic principles, concurrency, and system design. Each chapter consists of a brief review, followed by a broad and thought-provoking series of problems. We include a summary of data structure, algorithm, and problem solving patterns.",
        "previewLink": "No preview link",
        "isbn_13": "9781479274833",
        "original_path": "https://aibookshub.github.io/b1442/1442/Elements of Programming Interviews.pdf"
    },
    {
        "_id": "67f06b4acdd5f79c66494003",
        "id": "1442",
        "name": "Exercises for Programmers_ 57 Challenges to Develop Your Coding Skills 2015",
        "title": "Exercises for Programmers",
        "cover": "https://books.google.com/books/content?id=4sUNswEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "None",
        "author": "Brian P. Hogan",
        "summary": "One of the best ways to learn a programming language is to use it to solve problems. That's what this book is all about. Instead of questions rooted in theory, this book presents problems you'll encounter in everyday software development. Get sharp and stay sharp with more than fifty practice exercises rooted in real-world scenarios.",
        "previewLink": "No preview link",
        "isbn_13": "9781680501223",
        "original_path": "https://aibookshub.github.io/b1442/1442/Exercises for Programmers_ 57 Challenges to Develop Your Coding Skills 2015.pdf"
    },
    {
        "_id": "67f06b4bcdd5f79c66494004",
        "id": "1442",
        "name": "Interview Experience",
        "title": "301 Smart Answers to Tough Interview Questions",
        "cover": "https://books.google.com/books/content?id=qBDH76tl5-YC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Sourcebooks, Inc.",
        "author": "Vicky Oliver",
        "summary": "Packed full of the toughest interview questions and the savvy answers today's managers are looking for, this is the definitive guide to landing a job.",
        "previewLink": "No preview link",
        "isbn_13": "9781402203855",
        "original_path": "https://aibookshub.github.io/b1442/1442/Interview Experience.pdf"
    },
    {
        "_id": "67f06b4ccdd5f79c66494005",
        "id": "1442",
        "name": "Land the Tech Job You Love",
        "title": "Land the Tech Job You Love",
        "cover": "https://books.google.com/books/content?id=32bZPAAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "Pragmatic Life",
        "author": "Andy Lester",
        "summary": "This title shows you how to make and maintain the connections that will drive your future career moves. It pulls no punches and lays out the details for what gets you an interview, and gets you hired in a job in the technical world that makes you happy.",
        "previewLink": "No preview link",
        "isbn_13": "9781934356265",
        "original_path": "https://aibookshub.github.io/b1442/1442/Land the Tech Job You Love.pdf"
    },
    {
        "_id": "67f06b4ccdd5f79c66494006",
        "id": "1442",
        "name": "LetMeRead.net__Routledge.Exercises.in.Programming.Style.2nd.Edition.0367350203",
        "title": "LetMeRead.net__Routledge.Exercises.in.Programming.Style.2nd.Edition.0367350203",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "Unknown publisher",
        "author": "Unknown Author",
        "summary": "No summary available",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1442/1442/LetMeRead.net__Routledge.Exercises.in.Programming.Style.2nd.Edition.0367350203.pdf"
    },
    {
        "_id": "67f06b4dcdd5f79c66494007",
        "id": "1442",
        "name": "Pandas Exercises for Data Analysis",
        "title": "Pandas Workout",
        "cover": "https://books.google.com/books/content?id=8GcFEQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Simon and Schuster",
        "author": "Reuven Lerner",
        "summary": "DESCRIPTION Practice makes perfect pandas. Work out your pandas skills against dozens of real-world challenges, each carefully designed to build an intuitive knowledge of essential pandas tasks. In Pandas Workout, discover 50 exercises that will strengthen your pandas skills to a level of automatic fluency. You'll test yourself against common pandas challenges such as data cleaning, and explore real-world datasets such as New York Taxis, Kickstarter projects, and global tourist spending. Detailed explanations help guide your success and make your new skills stick. You'll even get a big boost to productivity, with tasks that used to mean a trip to StackOverflow now a natural part of your skillset.",
        "previewLink": "No preview link",
        "isbn_13": "9781617299728",
        "original_path": "https://aibookshub.github.io/b1442/1442/Pandas Exercises for Data Analysis.pdf"
    },
    {
        "_id": "67f06b4ecdd5f79c66494008",
        "id": "1442",
        "name": "Programming Interviews Exposed - Third Edition",
        "title": "Programming Interviews Exposed",
        "cover": "https://books.google.com/books/content?id=FQzczWtdm3gC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "John Mongan",
        "summary": "The pressure is on during the interview process but with the right preparation, you can walk away with your dream job. This classic book uncovers what interviews are really like at America's top software and computer companies and provides you with the tools to succeed in any situation. The authors take you step-by-step through new problems and complex brainteasers they were asked during recent technical interviews. 50 interview scenarios are presented along with in-depth analysis of the possible solutions. The problem-solving process is clearly illustrated so you'll be able to easily apply what you've learned during crunch time. You'll also find expert tips on what questions to ask, how to approach a problem, and how to recover if you become stuck. All of this will help you ace the interview and get the job you want. What you will learn from this book Tips for effectively completing the job application Ways to prepare for the entire programming interview process How to find the kind o",
        "previewLink": "No preview link",
        "isbn_13": "9781118169384",
        "original_path": "https://aibookshub.github.io/b1442/1442/Programming Interviews Exposed - Third Edition.pdf"
    },
    {
        "_id": "67f06b4ecdd5f79c66494009",
        "id": "1442",
        "name": "Programming_Interviews_Exposed_Coding_Your_Way_Through_the_Interview",
        "title": "Programming Interviews Exposed",
        "cover": "https://books.google.com/books/content?id=QKtTDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "John Mongan",
        "summary": "Ace technical interviews with smart preparation Programming Interviews Exposed is the programmer’s ideal first choice for technical interview preparation. Updated to reflect changing techniques and trends, this new fourth edition provides insider guidance on the unique interview process that today's programmers face. Online coding contests are being used to screen candidate pools of thousands, take-home projects have become commonplace, and employers are even evaluating a candidate's public code repositories at GitHub—and with competition becoming increasingly fierce, programmers need to shape themselves into the ideal candidate well in advance of the interview. This book doesn't just give you a collection of questions and answers, it walks you through the process of coming up with the solution so you learn the skills and techniques to shine on whatever problems you’re given. This edition combines a thoroughly revised basis in classic questions involving fundamental data structures and",
        "previewLink": "No preview link",
        "isbn_13": "9781119418481",
        "original_path": "https://aibookshub.github.io/b1442/1442/Programming_Interviews_Exposed_Coding_Your_Way_Through_the_Interview.pdf"
    },
    {
        "_id": "67f06b4fcdd5f79c6649400a",
        "id": "1442",
        "name": "Python For Data Analysis by Boston University",
        "title": "Python Data Analysis",
        "cover": "https://books.google.com/books/content?id=BqEbBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Packt Publishing Ltd",
        "author": "Ivan Idris",
        "summary": "This book is for programmers, scientists, and engineers who have knowledge of the Python language and know the basics of data science. It is for those who wish to learn different data analysis methods using Python and its libraries. This book contains all the basic ingredients you need to become an expert data analyst.",
        "previewLink": "No preview link",
        "isbn_13": "9781783553365",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python For Data Analysis by Boston University.pdf"
    },
    {
        "_id": "67f06b50cdd5f79c6649400b",
        "id": "1442",
        "name": "Python For Data Analysis Free EBook",
        "title": "Python Data Science Handbook",
        "cover": "https://books.google.com/books/content?id=6omNDQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "\"O'Reilly Media, Inc.\"",
        "author": "Jake VanderPlas",
        "summary": "For many researchers, Python is a first-class tool mainly because of its libraries for storing, manipulating, and gaining insight from data. Several resources exist for individual pieces of this data science stack, but only with the Python Data Science Handbook do you get them all—IPython, NumPy, Pandas, Matplotlib, Scikit-Learn, and other related tools. Working scientists and data crunchers familiar with reading and writing Python code will find this comprehensive desk reference ideal for tackling day-to-day issues: manipulating, transforming, and cleaning data; visualizing different types of data; and using data to build statistical or machine learning models. Quite simply, this is the must-have reference for scientific computing in Python. With this handbook, you’ll learn how to use: IPython and Jupyter: provide computational environments for data scientists using Python NumPy: includes the ndarray for efficient storage and manipulation of dense data arrays in Python Pandas: feature",
        "previewLink": "No preview link",
        "isbn_13": "9781491912133",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python For Data Analysis Free EBook.pdf"
    },
    {
        "_id": "67f06b51cdd5f79c6649400c",
        "id": "1442",
        "name": "Python for Data Analysis",
        "title": "Python for Data Analysis",
        "cover": "https://books.google.com/books/content?id=UiM3DwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "\"O'Reilly Media, Inc.\"",
        "author": "Wes McKinney",
        "summary": "Get complete instructions for manipulating, processing, cleaning, and crunching datasets in Python. Updated for Python 3.6, the second edition of this hands-on guide is packed with practical case studies that show you how to solve a broad set of data analysis problems effectively. You’ll learn the latest versions of pandas, NumPy, IPython, and Jupyter in the process. Written by Wes McKinney, the creator of the Python pandas project, this book is a practical, modern introduction to data science tools in Python. It’s ideal for analysts new to Python and for Python programmers new to data science and scientific computing. Data files and related material are available on GitHub. Use the IPython shell and Jupyter notebook for exploratory computing Learn basic and advanced features in NumPy (Numerical Python) Get started with data analysis tools in the pandas library Use flexible tools to load, clean, transform, merge, and reshape data Create informative visualizations with matplotlib Apply ",
        "previewLink": "No preview link",
        "isbn_13": "9781491957615",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python for Data Analysis.pdf"
    },
    {
        "_id": "67f06b51cdd5f79c6649400d",
        "id": "1442",
        "name": "python面试宝典",
        "title": "程序员面试宝典",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "欧立奇",
        "summary": "本书是《程序员面试宝典》的第二版,在保留第一版的数据结构、面向对象、程序设计等主干的基础上,使用各大IT公司及相关企业2007~2008年的最新面试题替换和补充原内容,以反映自第一版以来近2年的时间所发生的变化。",
        "previewLink": "No preview link",
        "isbn_13": "9787121073793",
        "original_path": "https://aibookshub.github.io/b1442/1442/python面试宝典.pdf"
    },
    {
        "_id": "67f06b52cdd5f79c6649400e",
        "id": "1442",
        "name": "Python面试通关宝典",
        "title": "Python面试通关宝典",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "洪锦魁",
        "summary": "本书内容分为两篇,第1篇是Python语言面试题,第2篇是算法面试题.Python语言面试题涵盖面试通用问题,Python语法面试题,函数,类,模块,文件管理,正则表达式以及Python语言综合应用;算法面试题涵盖排序,搜寻,字符串,数组,链表,二叉树,堆栈,数学问题,贪婪算法,动态规划算法以及综合应用.本书包括100多个问答题和300多个程序实例,帮助读者快速掌握Python语法与算法的知识.",
        "previewLink": "No preview link",
        "isbn_13": "9787302565017",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python面试通关宝典.pdf"
    },
    {
        "_id": "67f06b53cdd5f79c6649400f",
        "id": "1442",
        "name": "SQL Notes for Professionals",
        "title": "PHP Notes for Professionals",
        "cover": "https://books.google.com/books/content?id=fwU6EQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "EduGorilla Publication",
        "author": "Mr. Rohit Manglik",
        "summary": "EduGorilla Publication is a trusted name in the education sector, committed to empowering learners with high-quality study materials and resources. Specializing in competitive exams and academic support, EduGorilla provides comprehensive and well-structured content tailored to meet the needs of students across various streams and levels.",
        "previewLink": "No preview link",
        "isbn_13": "9789367849286",
        "original_path": "https://aibookshub.github.io/b1442/1442/SQL Notes for Professionals.pdf"
    },
    {
        "_id": "67f06b54cdd5f79c66494010",
        "id": "1442",
        "name": "The Google Resume",
        "title": "The Google Resume",
        "cover": "https://books.google.com/books/content?id=yQ3VngEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "Gayle Laakmann McDowell",
        "summary": "Describes how to land the job of one's dreams at a top tech company through choosing the correct major and extra-curricular activities in college, what other experiences appeal to employers and how to design and tailor one's resume.",
        "previewLink": "No preview link",
        "isbn_13": "9780470927625",
        "original_path": "https://aibookshub.github.io/b1442/1442/The Google Resume.pdf"
    },
    {
        "_id": "67f06b55cdd5f79c66494011",
        "id": "1442",
        "name": "The_Self_Taught_Programmer_The_Definitive_Guide",
        "title": "The Self-taught Programmer",
        "cover": "https://books.google.com/books/content?id=iZ4wEAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "Hachette UK",
        "author": "Cory Althoff",
        "summary": "'One of the best software design books of all time' - BookAuthority Cory Althoff is a self-taught programmer. After a year of self-study, he learned to program well enough to land a job as a software engineer II at eBay. But once he got there, he realised he was severely under-prepared. He was overwhelmed by the amount of things he needed to know but hadn't learned. His journey learning to program, and his experience in first software engineering job were the inspiration for this book. This book is not just about learning to program, although you will learn to code. If you want to program professionally, it is not enough to learn to code; that is why, in addition to helping you learn to program, Althoff also cover the rest of the things you need to know to program professionally that classes and books don't teach you. The Self-taught Programmer is a roadmap, a guide to take you from writing your first Python program to passing your first technical interview. The book is divided into fi",
        "previewLink": "No preview link",
        "isbn_13": "9781472147097",
        "original_path": "https://aibookshub.github.io/b1442/1442/The_Self_Taught_Programmer_The_Definitive_Guide.pdf"
    },
    {
        "_id": "67f06b55cdd5f79c66494012",
        "id": "1442",
        "name": "剑指offer - 名企面试官精讲典型编程题",
        "title": "剑指Offer",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "何海涛 (软件工程师)",
        "summary": "本书剖析了80个典型的编程面试题,系统整理基础知识,代码质量,解题思路,优化效率和综合能力这5个面试要点.",
        "previewLink": "No preview link",
        "isbn_13": "9787121310928",
        "original_path": "https://aibookshub.github.io/b1442/1442/剑指offer - 名企面试官精讲典型编程题.pdf"
    },
    {
        "_id": "67f06b56cdd5f79c66494013",
        "id": "1442",
        "name": "教你如何迅速秒杀掉：99%的海量数据处理面试题",
        "title": "教師專業發展",
        "cover": "https://books.google.com/books/content?id=G-P_CgAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "高等教育文化事業有限公司",
        "author": "高等教育出版",
        "summary": "應用「教學圈」支持教師專業發展的策略／黃旭鈞 國民小學推廣行動學習之關切階層研究／王令宜、高熏芳 歷史教師應具備的教學專業素養／單文經 蘇格蘭教學總會推動教師專業發展之歷史探究，1966／林仁傑 高職專業群科教師專業標準內涵之探究：以學校實務工作者觀點分析／許宛琪、胡茹萍 中國大陸教師專業標準及其應用分析／吳清基、邱于真 探思教師專業標準之發展與運用／潘慧玲 教師專業標準應用於教師評鑑之實務議題初探／甄曉蘭 杜威學習共同體的理念闡釋／單文經 教育專業發展的潛在危機與理想藍圖／林志成",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1442/1442/教你如何迅速秒杀掉：99%的海量数据处理面试题.pdf"
    },
    {
        "_id": "67f06b56cdd5f79c66494014",
        "id": "1442",
        "name": "编程之法：面试和算法心得",
        "title": "编程之法",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "July",
        "summary": "Ben shu she ji mian shi,Suan fa,Ji qi xue xi san ge zhu ti.Shu zhong de mei dao bian cheng ti mu dou ji chu le duo zhong si lu,Duo zhong jie fa,Bu duan you hua,Zhu ceng di jin.Quan shu gong 7 zhang,Di 1 zhang zhi di 6 zhang fen bie chan shu zi fu chuan,Shu zu,Shu,Cha zhao,Dong tai gui hua,Hai liang shu ju chu li deng xiang guan de bian cheng mian shi ti he suan fa;Di 7 zhang jie shao ji qi xue xi de liang ge suan faK jin lin he SVM.",
        "previewLink": "No preview link",
        "isbn_13": "9787115381613",
        "original_path": "https://aibookshub.github.io/b1442/1442/编程之法：面试和算法心得.pdf"
    },
    {
        "_id": "67f06b58cdd5f79c66494015",
        "id": "1442",
        "name": "编程之美—微软技术面试心得《编程之美》小组",
        "title": "出版人",
        "cover": "https://books.google.com/books/content?id=c9dMAQAAIAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "None",
        "author": "Unknown Author",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1442/1442/编程之美—微软技术面试心得《编程之美》小组.pdf"
    },
    {
        "_id": "67f06b58cdd5f79c66494016",
        "id": "1442",
        "name": "金领简历 - 敲开苹果、微软、谷歌的大门",
        "title": "金领简历",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "漆犇",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "9787115279262",
        "original_path": "https://aibookshub.github.io/b1442/1442/金领简历 - 敲开苹果、微软、谷歌的大门.pdf"
    },
    {
        "_id": "67f4047eeb8961eaf18d4067",
        "id": "1458",
        "name": "3209078_Python GUI设计——tkinter菜鸟编程_1_321_1581054929",
        "title": "3209078_Python GUI设计——tkinter菜鸟编程_1_321_1581054929",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "Unknown publisher",
        "author": "Unknown Author",
        "summary": "No summary available",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1458/1458/3209078_Python GUI设计——tkinter菜鸟编程_1_321_1581054929.pdf"
    },
    {
        "_id": "67f40484eb8961eaf18d4068",
        "id": "1458",
        "name": "Effective_Python_编写高质量Python代码的59个有效方法_Brett_Slatkin",
        "title": "Fifty-nine Specific Ways to Write Better Python",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Brett Slatkin",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "9780134034416",
        "original_path": "https://aibookshub.github.io/b1458/1458/Effective_Python_编写高质量Python代码的59个有效方法_Brett_Slatkin.pdf"
    },
    {
        "_id": "67f40488eb8961eaf18d4069",
        "id": "1458",
        "name": "Python GUI设计：tkinter菜鸟编程 [洪锦魁]",
        "title": "學會改變：戒除壞習慣、實現目標、影響他人的9大關鍵策略",
        "cover": "https://books.google.com/books/content?id=-RylDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "樂金文化（方言文化）",
        "author": "奇普‧希思、丹‧希思（Chip Heath and Dan Heath）",
        "summary": "紐約時報暢銷榜第一 為什麼戒菸每次都失敗？想早起運動卻爬不起來？ 我們都想變成更好的自己，但改變卻好困難！ 其實你不是懶惰或沒毅力，而是缺乏明確的指令、鮮明的情感，還有對的環境，或是用錯方法，所以改變很難成功。想要養成運動習慣？讓下屬變得不再遲到？還是希望工作團隊更有凝聚力？不論你是要改變自己、改變他人，還是改變組織，只要掌握3層面的行動架構，就能輕鬆改變、無痛成長。 我們的情感面就像大象，而理智面則是騎象人，騎象人手持韁繩，看似能控制大象，但兩者的力量實在過於懸殊，當雙方意見不合時，騎象人完全不是大象的對手，很容易敗下陣來，被大象拖著跑。 因此，如果想讓改變成功，你需要給予清晰的指令，並從情感面著手，避免因疲乏而半途而廢，最後再塑造容易改變的環境，引導大象走在正確且順暢的道路上。 本書作者是暢銷作家希思兄弟，他們在大量行為研究的基礎上，通過詳實有趣的案例，告訴我們如何掌握3層面的行動架構：理智面〈指揮騎象人〉、情感面〈激勵大象〉、環境面（形塑路徑），並提供9大關鍵策略，不論你是想要改變，還是正在改變，這本書都是你的最佳實用指南。 ◎成功改變的3層行動架構 ‧第一層：理智面〈指揮騎象人〉 我們有時候抗拒改變，可能是因為指示不清楚，所以想成功改變必須提出清晰明確的行動指令。如果想讓員工更積極，不要只是叫他們「要更加努力」，而是應該規定「每個月至少要打125通電話給客戶」。 ‧第二層：情感面〈激勵大象〉 我們以為是懶惰讓改變失敗，但通常是因為意志力已經疲乏。騎象人沒辦法長時間控制住大象，所以能否觸動情感面是關鍵。希望實驗室研發了一款電玩，讓小病友和裡面的奈米抗癌機器人產生情感連結，成功將化療藥物的服用率提高20％，存活率因此提高一倍。 ‧第三層：環境面〈形塑路徑〉 當你規劃好改變的路徑，成功的機率就會增加，因為當情境產生變化，行為就會跟著改變。亞馬遜的網站設計師在網頁上新增「一鍵下單」的功能，將購物時的操作障礙降到最低，就讓公司增加好幾百萬美元的營收。 本書特色 ★全球媒體一致好評 美國《時代雜誌》列為「使你更有思想的20本書之一」，《華盛頓郵報》、《彭博商業周刊》等全球指標性媒體好評不斷。 ★結合跨領域知識 結合心理學、認知科學、神經科學和行為設計學等知識，提供最有效的行動策略。 ★具備實用價值 包含大量有趣的案例，適合管理者、創業者以及所有想要改變自己、影響他人、實",
        "previewLink": "No preview link",
        "isbn_13": "9789869735087",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python GUI设计：tkinter菜鸟编程 [洪锦魁].pdf"
    },
    {
        "_id": "67f4048feb8961eaf18d406a",
        "id": "1458",
        "name": "Python3网络爬虫数据采集",
        "title": "机器学习实战",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Unknown Author",
        "summary": "本书通过精心编排的实例,切入日常工作任务,摒弃学术化语言,利用高效可复用的Python代码阐释如何处理统计数据,进行数据分析及可视化.读者可从中学到一些核心的机器学习算法,并将其运用于某些策略性任务中,如分类,预测及推荐等.",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python3网络爬虫数据采集.pdf"
    },
    {
        "_id": "67f404a8e0a881fffe1703dc",
        "id": "1458",
        "name": "3209078_Python GUI设计——tkinter菜鸟编程_1_321_1581054929",
        "title": "3209078_Python GUI设计——tkinter菜鸟编程_1_321_1581054929",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "Unknown publisher",
        "author": "Unknown Author",
        "summary": "No summary available",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1458/1458/3209078_Python GUI设计——tkinter菜鸟编程_1_321_1581054929.pdf"
    },
    {
        "_id": "67f404ace0a881fffe1703dd",
        "id": "1458",
        "name": "Effective_Python_编写高质量Python代码的59个有效方法_Brett_Slatkin",
        "title": "Fifty-nine Specific Ways to Write Better Python",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Brett Slatkin",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "9780134034416",
        "original_path": "https://aibookshub.github.io/b1458/1458/Effective_Python_编写高质量Python代码的59个有效方法_Brett_Slatkin.pdf"
    },
    {
        "_id": "67f404afe0a881fffe1703de",
        "id": "1458",
        "name": "Python GUI设计：tkinter菜鸟编程 [洪锦魁]",
        "title": "學會改變：戒除壞習慣、實現目標、影響他人的9大關鍵策略",
        "cover": "https://books.google.com/books/content?id=-RylDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "樂金文化（方言文化）",
        "author": "奇普‧希思、丹‧希思（Chip Heath and Dan Heath）",
        "summary": "紐約時報暢銷榜第一 為什麼戒菸每次都失敗？想早起運動卻爬不起來？ 我們都想變成更好的自己，但改變卻好困難！ 其實你不是懶惰或沒毅力，而是缺乏明確的指令、鮮明的情感，還有對的環境，或是用錯方法，所以改變很難成功。想要養成運動習慣？讓下屬變得不再遲到？還是希望工作團隊更有凝聚力？不論你是要改變自己、改變他人，還是改變組織，只要掌握3層面的行動架構，就能輕鬆改變、無痛成長。 我們的情感面就像大象，而理智面則是騎象人，騎象人手持韁繩，看似能控制大象，但兩者的力量實在過於懸殊，當雙方意見不合時，騎象人完全不是大象的對手，很容易敗下陣來，被大象拖著跑。 因此，如果想讓改變成功，你需要給予清晰的指令，並從情感面著手，避免因疲乏而半途而廢，最後再塑造容易改變的環境，引導大象走在正確且順暢的道路上。 本書作者是暢銷作家希思兄弟，他們在大量行為研究的基礎上，通過詳實有趣的案例，告訴我們如何掌握3層面的行動架構：理智面〈指揮騎象人〉、情感面〈激勵大象〉、環境面（形塑路徑），並提供9大關鍵策略，不論你是想要改變，還是正在改變，這本書都是你的最佳實用指南。 ◎成功改變的3層行動架構 ‧第一層：理智面〈指揮騎象人〉 我們有時候抗拒改變，可能是因為指示不清楚，所以想成功改變必須提出清晰明確的行動指令。如果想讓員工更積極，不要只是叫他們「要更加努力」，而是應該規定「每個月至少要打125通電話給客戶」。 ‧第二層：情感面〈激勵大象〉 我們以為是懶惰讓改變失敗，但通常是因為意志力已經疲乏。騎象人沒辦法長時間控制住大象，所以能否觸動情感面是關鍵。希望實驗室研發了一款電玩，讓小病友和裡面的奈米抗癌機器人產生情感連結，成功將化療藥物的服用率提高20％，存活率因此提高一倍。 ‧第三層：環境面〈形塑路徑〉 當你規劃好改變的路徑，成功的機率就會增加，因為當情境產生變化，行為就會跟著改變。亞馬遜的網站設計師在網頁上新增「一鍵下單」的功能，將購物時的操作障礙降到最低，就讓公司增加好幾百萬美元的營收。 本書特色 ★全球媒體一致好評 美國《時代雜誌》列為「使你更有思想的20本書之一」，《華盛頓郵報》、《彭博商業周刊》等全球指標性媒體好評不斷。 ★結合跨領域知識 結合心理學、認知科學、神經科學和行為設計學等知識，提供最有效的行動策略。 ★具備實用價值 包含大量有趣的案例，適合管理者、創業者以及所有想要改變自己、影響他人、實",
        "previewLink": "No preview link",
        "isbn_13": "9789869735087",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python GUI设计：tkinter菜鸟编程 [洪锦魁].pdf"
    },
    {
        "_id": "67f404b2e0a881fffe1703df",
        "id": "1458",
        "name": "Python3网络爬虫数据采集",
        "title": "机器学习实战",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Unknown Author",
        "summary": "本书通过精心编排的实例,切入日常工作任务,摒弃学术化语言,利用高效可复用的Python代码阐释如何处理统计数据,进行数据分析及可视化.读者可从中学到一些核心的机器学习算法,并将其运用于某些策略性任务中,如分类,预测及推荐等.",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python3网络爬虫数据采集.pdf"
    },
    {
        "_id": "67f404b6e0a881fffe1703e0",
        "id": "1458",
        "name": "Python_And_Tkinter_Programming_ElectroVolt.ir_",
        "title": "Beginning Programming with Python For Dummies",
        "cover": "https://books.google.com/books/content?id=vEpGDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "John Paul Mueller",
        "summary": "The easy way to learn programming fundamentals with Python Python is a remarkably powerful and dynamic programming language that's used in a wide variety of application domains. Some of its key distinguishing features include a very clear, readable syntax, strong introspection capabilities, intuitive object orientation, and natural expression of procedural code. Plus, Python features full modularity, supporting hierarchical packages, exception-based error handling, and modules easily written in C, C++, Java, R, or .NET languages, such as C#. In addition, Python supports a number of coding styles that include: functional, imperative, object-oriented, and procedural. Due to its ease of use and flexibility, Python is constantly growing in popularity—and now you can wear your programming hat with pride and join the ranks of the pros with the help of this guide. Inside, expert author John Paul Mueller gives a complete step-by-step overview of all there is to know about Python. From performi",
        "previewLink": "No preview link",
        "isbn_13": "9781119457893",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python_And_Tkinter_Programming_ElectroVolt.ir_.pdf"
    },
    {
        "_id": "67f404b9e0a881fffe1703e1",
        "id": "1458",
        "name": "Python与Tkinter编程(jb51.net)",
        "title": "你也能看得懂的Python算法书",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "王硕",
        "summary": "本书首先介绍当下流程的编程语言Python,详细讲解Python语言中的变量和顺序,分支,循环三大结构,以及列表和函数的使用.然后以通俗易懂的语言讲解了双指针,哈希,深度优先,广度优先,回溯,贪心,动态规划和最短路径等经典算法.",
        "previewLink": "No preview link",
        "isbn_13": "9787121352553",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python与Tkinter编程(jb51.net).pdf"
    },
    {
        "_id": "67f404bbe0a881fffe1703e2",
        "id": "1458",
        "name": "Python网络爬虫从入门到实践.html",
        "title": "Python 從網路爬蟲到生活應用超實務",
        "cover": "https://books.google.com/books/content?id=XcQiEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "博碩",
        "author": "陳會安",
        "summary": "☀ 科技來自於人性，讓程式設計回歸生活上的應用！ ☀ 本書不只讓你學會Python，還要讓它「真正」進入你的日常生活！ 內容簡介 人工智慧世代必備的資料擷取術 ─ 網路爬蟲，幫你建立 Python 網路爬蟲 SOP 標準作業程序。 ☛ 資料是王 ( Data is King )，誰擁有資料，誰就能主宰世界。從 Python 網路爬蟲到生活應用，完整說明你需要必備的 Python 資料擷取術。 ☛ 網路爬蟲就是從 HTML 網頁取得資料。你可以想像在 Web 星球 ( WWW ) 上有眾多果園 ( 網站 ) 和 HTML 果樹 ( 網頁 )，你的工作是拿著水果籃進入指定的果園後，爬上果樹摘下樹上的水果 ( HTML 標籤 )，你需要定位水果在哪裡以及規劃摘取順序，才能成功摘下整棵樹的水果，放進水果籃。 ☛ 本書讓你學得到 Python，用得到 Python，還能夠「真正活用」Python 來解決你日常生活、學習和工作上，各種資料擷取和處理的問題。 適用讀者 ✎ 已經有其他程式語言基礎、或對運算思維有興趣的初學者。 ✎ 適合讀者自學 Python 程式設計，亦可作為 Python 程式設計相關課程的上課教材。",
        "previewLink": "No preview link",
        "isbn_13": "9789864345397",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python网络爬虫从入门到实践.html.pdf"
    },
    {
        "_id": "67f404bfe0a881fffe1703e3",
        "id": "1458",
        "name": "Python网络爬虫从入门到实践第2版.html",
        "title": "Python 從網路爬蟲到生活應用超實務",
        "cover": "https://books.google.com/books/content?id=XcQiEAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "博碩",
        "author": "陳會安",
        "summary": "☀ 科技來自於人性，讓程式設計回歸生活上的應用！ ☀ 本書不只讓你學會Python，還要讓它「真正」進入你的日常生活！ 內容簡介 人工智慧世代必備的資料擷取術 ─ 網路爬蟲，幫你建立 Python 網路爬蟲 SOP 標準作業程序。 ☛ 資料是王 ( Data is King )，誰擁有資料，誰就能主宰世界。從 Python 網路爬蟲到生活應用，完整說明你需要必備的 Python 資料擷取術。 ☛ 網路爬蟲就是從 HTML 網頁取得資料。你可以想像在 Web 星球 ( WWW ) 上有眾多果園 ( 網站 ) 和 HTML 果樹 ( 網頁 )，你的工作是拿著水果籃進入指定的果園後，爬上果樹摘下樹上的水果 ( HTML 標籤 )，你需要定位水果在哪裡以及規劃摘取順序，才能成功摘下整棵樹的水果，放進水果籃。 ☛ 本書讓你學得到 Python，用得到 Python，還能夠「真正活用」Python 來解決你日常生活、學習和工作上，各種資料擷取和處理的問題。 適用讀者 ✎ 已經有其他程式語言基礎、或對運算思維有興趣的初學者。 ✎ 適合讀者自學 Python 程式設計，亦可作為 Python 程式設計相關課程的上課教材。",
        "previewLink": "No preview link",
        "isbn_13": "9789864345397",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python网络爬虫从入门到实践第2版.html.pdf"
    },
    {
        "_id": "67f404c1e0a881fffe1703e4",
        "id": "1458",
        "name": "Python自动化运维  技术与最佳实践",
        "title": "Python自動化的樂趣",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Al Sweigart",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "9789864762729",
        "original_path": "https://aibookshub.github.io/b1458/1458/Python自动化运维  技术与最佳实践.pdf"
    },
    {
        "_id": "67f404c3e0a881fffe1703e5",
        "id": "1458",
        "name": "Tkinter GUI Application Development Blueprints",
        "title": "Tkinter GUI Application Development Blueprints, Second Edition",
        "cover": "https://books.google.com/books/content?id=5gxTDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Packt Publishing Ltd",
        "author": "Bhaskar Chaudhary",
        "summary": "Geometry Management, Event Handling, and more Key Features A Practical, guide to learn the application of Python and GUI programming with tkinter Create multiple cross-platform real-world projects by integrating host of third party libraries and tools Learn to build beautiful and highly interactive user interfaces, targeting multiple devices. Book Description Tkinter is the built-in GUI package that comes with standard Python distributions. It is a cross-platform package, which means you build once and deploy everywhere. It is simple to use and intuitive in nature, making it suitable for programmers and non-programmers alike. This book will help you master the art of GUI programming. It delivers the bigger picture of GUI programming by building real-world, productive, and fun applications such as a text editor, drum machine, game of chess, audio player, drawing application, piano tutor, chat application, screen saver, port scanner, and much more. In every project, you will build on the",
        "previewLink": "No preview link",
        "isbn_13": "9781788834452",
        "original_path": "https://aibookshub.github.io/b1458/1458/Tkinter GUI Application Development Blueprints.pdf"
    },
    {
        "_id": "67f404c6e0a881fffe1703e6",
        "id": "1458",
        "name": "Tkinter GUI Application Development Hotshot",
        "title": "Tkinter GUI Application Development Hotshot",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Bhaskar Chaudhary",
        "summary": "Practical, real-world example projects. Start with the topics that grab your attention or work through each project in sequence. If you have just started with GUI programming, this book is ideal for you. This book is also great if you are an experienced software developer, scientist, researcher, engineer, student, or hobbyist.",
        "previewLink": "No preview link",
        "isbn_13": "9781461949350",
        "original_path": "https://aibookshub.github.io/b1458/1458/Tkinter GUI Application Development Hotshot.pdf"
    },
    {
        "_id": "67f404c8e0a881fffe1703e7",
        "id": "1458",
        "name": "tkinter-gui-programming-example",
        "title": "Tkinter GUI Programming by Example",
        "cover": "https://books.google.com/books/content?id=KM85tAEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "None",
        "author": "David Love",
        "summary": "Leverage the power of Python and its de facto GUI framework to build highly interactive interfaces Key Features The fundamentals of Python and GUI programming with Tkinter. Create multiple cross-platform projects by integrating a host of third-party libraries and tools. Build beautiful and highly-interactive user interfaces that target multiple devices. Book Description Tkinter is a modular, cross-platform application development toolkit for Python. When developing GUI-rich applications, the most important choices are which programming language(s) and which GUI framework to use. Python and Tkinter prove to be a great combination. This book will get you familiar with Tkinter by having you create fun and interactive projects. These projects have varying degrees of complexity. We'll start with a simple project, where you'll learn the fundamentals of GUI programming and the basics of working with a Tkinter application. After getting the basics right, we'll move on to creating a project of ",
        "previewLink": "No preview link",
        "isbn_13": "9781788627481",
        "original_path": "https://aibookshub.github.io/b1458/1458/tkinter-gui-programming-example.pdf"
    },
    {
        "_id": "67f404cce0a881fffe1703e8",
        "id": "1458",
        "name": "用Python写网络爬虫",
        "title": "用Python写网络爬虫(第2版)",
        "cover": "https://books.google.com/books/content?id=Z3H-EAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Packt Publishing Ltd",
        "author": "Posts & Telecom Press",
        "summary": "史上首本Python网络爬虫图书全新升级版 上一版年度销量近40000册 针对Python 3.x编写 提供示例完整源码和实例网站搭建源码 Key Features 本书是使用Python 3.x的最新特性来爬取网络数据的权威指南。 提供示例完整源码和实例网站搭建源码 Book Description 史上首本Python网络爬虫图书全新升级版，上一版年度销量近40000册。 针对Python 3.x版本编写。 提供示例完整源码和实例网站搭建源码，确保用户能在本地成功复现爬取网站环境，并保障网站的稳定性与可靠性以及代码运行结果的可再现性。 Internet上包含了许多有用的数据，其中大部分是可以免费公开访问的。但是，这些数据不容易使用，它们内嵌在网站的架构和样式中，在提取时也需要多加小心。网络爬取技术作为一种收集和理解网络上海量信息的方式，正变得越来越有用。 本书是使用Python 3.x的最新特性来爬取网络数据的权威指南。本书讲解了从静态网站提取数据的方法，以及如何使用数据库和文件缓存技术来节省时间并管理服务器负载，然后介绍了如何使用浏览器、爬虫和并发爬虫开发一个更为复杂的爬虫。 借助于PyQt和Selenium，你可以决定何时以及如何从依赖JavaScript的网站上爬取数据，以及更好地理解在受CAPTCHA保护的复杂网站上提交表单的方法。本书还讲解了使用Python包（比如mechanize）进行自动化处理的方法、使用Scrapy库创建基于类的爬虫的方法，以及如何在真实的网站上实施所学的爬虫技巧。 本书最后还涵盖了使用爬虫对网站进行测试、远程爬取技术、图像处理以及其他相关的主题。 本书主要内容如下： 使用简单的Python程序从页面中提取数据； 构建并发爬虫，对页面进行并行处理； 通过跟踪链接来爬取一个网站； 从HTML中提取特性； 缓存下载的HTML，以供复用； 比较并发模型，确定最快的爬虫； 解析依赖于JavaScript的网站； 与表单和会话进行交互。 What will you learn 使用简单的Python程序从页面中提取数据； 构建并发爬虫，对页面进行并行处理； 通过跟踪链接来爬取一个网站； 从HTML中提取特性； 缓存下载的HTML，以供复用； 比较并发模型，确定最快的爬虫； 解析依赖于JavaScript的网站； 与表单和会话进行交互。 W",
        "previewLink": "No preview link",
        "isbn_13": "9781835888513",
        "original_path": "https://aibookshub.github.io/b1458/1458/用Python写网络爬虫.pdf"
    },
    {
        "_id": "67f404cee0a881fffe1703e9",
        "id": "1458",
        "name": "网络爬虫－Python和数据分析",
        "title": "用Python写网络爬虫(第2版)",
        "cover": "https://books.google.com/books/content?id=Z3H-EAAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Packt Publishing Ltd",
        "author": "Posts & Telecom Press",
        "summary": "史上首本Python网络爬虫图书全新升级版 上一版年度销量近40000册 针对Python 3.x编写 提供示例完整源码和实例网站搭建源码 Key Features 本书是使用Python 3.x的最新特性来爬取网络数据的权威指南。 提供示例完整源码和实例网站搭建源码 Book Description 史上首本Python网络爬虫图书全新升级版，上一版年度销量近40000册。 针对Python 3.x版本编写。 提供示例完整源码和实例网站搭建源码，确保用户能在本地成功复现爬取网站环境，并保障网站的稳定性与可靠性以及代码运行结果的可再现性。 Internet上包含了许多有用的数据，其中大部分是可以免费公开访问的。但是，这些数据不容易使用，它们内嵌在网站的架构和样式中，在提取时也需要多加小心。网络爬取技术作为一种收集和理解网络上海量信息的方式，正变得越来越有用。 本书是使用Python 3.x的最新特性来爬取网络数据的权威指南。本书讲解了从静态网站提取数据的方法，以及如何使用数据库和文件缓存技术来节省时间并管理服务器负载，然后介绍了如何使用浏览器、爬虫和并发爬虫开发一个更为复杂的爬虫。 借助于PyQt和Selenium，你可以决定何时以及如何从依赖JavaScript的网站上爬取数据，以及更好地理解在受CAPTCHA保护的复杂网站上提交表单的方法。本书还讲解了使用Python包（比如mechanize）进行自动化处理的方法、使用Scrapy库创建基于类的爬虫的方法，以及如何在真实的网站上实施所学的爬虫技巧。 本书最后还涵盖了使用爬虫对网站进行测试、远程爬取技术、图像处理以及其他相关的主题。 本书主要内容如下： 使用简单的Python程序从页面中提取数据； 构建并发爬虫，对页面进行并行处理； 通过跟踪链接来爬取一个网站； 从HTML中提取特性； 缓存下载的HTML，以供复用； 比较并发模型，确定最快的爬虫； 解析依赖于JavaScript的网站； 与表单和会话进行交互。 What will you learn 使用简单的Python程序从页面中提取数据； 构建并发爬虫，对页面进行并行处理； 通过跟踪链接来爬取一个网站； 从HTML中提取特性； 缓存下载的HTML，以供复用； 比较并发模型，确定最快的爬虫； 解析依赖于JavaScript的网站； 与表单和会话进行交互。 W",
        "previewLink": "No preview link",
        "isbn_13": "9781835888513",
        "original_path": "https://aibookshub.github.io/b1458/1458/网络爬虫－Python和数据分析.pdf"
    }
];
