export const booklist = [
    {
        "id": "1442",
        "name": "21 Types of SQL Join",
        "title": "Advanced ANSI SQL Data Modeling and Structure Processing",
        "cover": "http://books.google.com/books/content?id=6aMJH43GwpIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Artech House",
        "author": "Michael M. David",
        "summary": "This new book is an essential tool for utilizing the ANSI SQL outer join operation, and an indispensable guide to using this operation to perform simple or complex data modeling. It provides a comprehensive look at the outer join operation, its powerful syntax, and new features and capabilities that can be developed based on the operation's data modeling capacity.",
        "previewLink": "No preview link",
        "isbn_13": "9781580530385",
        "original_path": "https://aibookshub.github.io/b1442/1442/21 Types of SQL Join.pdf"
    },
    {
        "id": "1442",
        "name": "26 Pages Pandas",
        "title": "Pandas",
        "cover": "http://books.google.com/books/content?id=05ivSsL4EpIC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Gareth Stevens Publishing LLLP",
        "author": "Susan Kueffner",
        "summary": "Describes the physical characteristics, habitat, and behavior of pandas.",
        "previewLink": "No preview link",
        "isbn_13": "9780836891003",
        "original_path": "https://aibookshub.github.io/b1442/1442/26 Pages Pandas.pdf"
    },
    {
        "id": "1442",
        "name": "Ace the Programming Interview - 160 Questions and Answers for Success",
        "title": "Ace the Programming Interview",
        "cover": "http://books.google.com/books/content?id=DEn71rgH4_4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "Edward Guiness",
        "summary": "Be prepared to answer the most relevant interview questions and land the job Programmers are in demand, but to land the job, you must demonstrate knowledge of those things expected by today's employers. This guide sets you up for success. Not only does it provide 160 of the most commonly asked interview questions and model answers, but it also offers insight into the context and motivation of hiring managers in today's marketplace. Written by a veteran hiring manager, this book is a comprehensive guide for experienced and first-time programmers alike. Provides insight into what drives the recruitment process and how hiring managers think Covers both practical knowledge and recommendations for handling the interview process Features 160 actual interview questions, including some related to code samples that are available for download on a companion website Includes information on landing an interview, preparing a cheat-sheet for a phone interview, how to demonstrate your programming wis",
        "previewLink": "No preview link",
        "isbn_13": "9781118518564",
        "original_path": "https://aibookshub.github.io/b1442/1442/Ace the Programming Interview - 160 Questions and Answers for Success.pdf"
    },
    {
        "id": "1442",
        "name": "Addison.Wesley.-.The.Pragmatic.Programmer.1ed.1999.程序员修炼之道",
        "title": "代码大全",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "Unknown Author",
        "summary": "软件构建之实践指南",
        "previewLink": "No preview link",
        "isbn_13": "9787121046186",
        "original_path": "https://aibookshub.github.io/b1442/1442/Addison.Wesley.-.The.Pragmatic.Programmer.1ed.1999.程序员修炼之道.pdf"
    },
    {
        "id": "1442",
        "name": "Clean Code Handbook - LeetCode 50 Common Interview Questions",
        "title": "Elements of Programming Interviews",
        "cover": "http://books.google.com/books/content?id=y6FLBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "EPI",
        "author": "Adnan Aziz",
        "summary": "The core of EPI is a collection of over 300 problems with detailed solutions, including 100 figures, 250 tested programs, and 150 variants. The problems are representative of questions asked at the leading software companies. The book begins with a summary of the nontechnical aspects of interviewing, such as common mistakes, strategies for a great interview, perspectives from the other side of the table, tips on negotiating the best offer, and a guide to the best ways to use EPI. The technical core of EPI is a sequence of chapters on basic and advanced data structures, searching, sorting, broad algorithmic principles, concurrency, and system design. Each chapter consists of a brief review, followed by a broad and thought-provoking series of problems. We include a summary of data structure, algorithm, and problem solving patterns.",
        "previewLink": "No preview link",
        "isbn_13": "9781479274833",
        "original_path": "https://aibookshub.github.io/b1442/1442/Clean Code Handbook - LeetCode 50 Common Interview Questions.pdf"
    },
    {
        "id": "1442",
        "name": "Coding Interviews - Questions, Analysis & Solutions",
        "title": "Coding Interviews",
        "cover": "http://books.google.com/books/content?id=p4UcrLAYzd4C&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Apress",
        "author": "Harry He",
        "summary": "This book is about coding interview questions from software and Internet companies. It covers five key factors which determine performance of candidates: (1) the basics of programming languages, data structures and algorithms, (2) approaches to writing code with high quality, (3) tips to solve difficult problems, (4) methods to optimize code, (5) soft skills required in interviews. The basics of languages, algorithms and data structures are discussed as well as questions that explore how to write robust solutions after breaking down problems into manageable pieces. It also includes examples to focus on modeling and creative problem solving. Interview questions from the most popular companies in the IT industry are taken as examples to illustrate the five factors above. Besides solutions, it contains detailed analysis, how interviewers evaluate solutions, as well as why they like or dislike them. The author makes clever use of the fact that interviewees will have limited time to program",
        "previewLink": "No preview link",
        "isbn_13": "9781430247623",
        "original_path": "https://aibookshub.github.io/b1442/1442/Coding Interviews - Questions, Analysis & Solutions.pdf"
    },
    {
        "id": "1442",
        "name": "Cracking the Coding Interview - 150 Programming Interview Questions and Solutions 4e Small",
        "title": "Cracking the Coding Interview",
        "cover": "http://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking the Coding Interview - 150 Programming Interview Questions and Solutions 4e Small.pdf"
    },
    {
        "id": "1442",
        "name": "Cracking the Coding Interview, 4 Edition - 150 Programming Interview Questions and Solutions",
        "title": "Cracking the Coding Interview",
        "cover": "http://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking the Coding Interview, 4 Edition - 150 Programming Interview Questions and Solutions.pdf"
    },
    {
        "id": "1442",
        "name": "Cracking the Coding Interview, 6th Edition",
        "title": "Cracking the Coding Interview",
        "cover": "http://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking the Coding Interview, 6th Edition.pdf"
    },
    {
        "id": "1442",
        "name": "Cracking_the_Coding_Interview_6th_Edition_189_Programming_Questions",
        "title": "Cracking the Coding Interview",
        "cover": "http://books.google.com/books/content?id=anhAXwAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "CreateSpace",
        "author": "Gayle Laakmann McDowell",
        "summary": "Now in the 5th edition, Cracking the Coding Interview gives you the interview preparation you need to get the top software developer jobs. This book provides: 150 Programming Interview Questions and Solutions: From binary trees to binary search, this list of 150 questions includes the most common and most useful questions in data structures, algorithms, and knowledge based questions. 5 Algorithm Approaches: Stop being blind-sided by tough algorithm questions, and learn these five approaches to tackle the trickiest problems. Behind the Scenes of the interview processes at Google, Amazon, Microsoft, Facebook, Yahoo, and Apple: Learn what really goes on during your interview day and how decisions get made. Ten Mistakes Candidates Make -- And How to Avoid Them: Don't lose your dream job by making these common mistakes. Learn what many candidates do wrong, and how to avoid these issues. Steps to Prepare for Behavioral and Technical Questions: Stop meandering through an endless set of questi",
        "previewLink": "No preview link",
        "isbn_13": "9781466208681",
        "original_path": "https://aibookshub.github.io/b1442/1442/Cracking_the_Coding_Interview_6th_Edition_189_Programming_Questions.pdf"
    },
    {
        "id": "1442",
        "name": "Data Cleaning Guidelines",
        "title": "Best Practices in Data Cleaning",
        "cover": "http://books.google.com/books/content?id=G8V1AwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "SAGE Publications",
        "author": "Jason W. Osborne",
        "summary": "Many researchers jump from data collection directly into testing hypothesis without realizing these tests can go profoundly wrong without clean data. This book provides a clear, accessible, step-by-step process of important best practices in preparing for data collection, testing assumptions, and examining and cleaning data in order to decrease error rates and increase both the power and replicability of results. Jason W. Osborne, author of the handbook Best Practices in Quantitative Methods (SAGE, 2008) provides easily-implemented suggestions that are evidence-based and will motivate change in practice by empirically demonstrating—for each topic—the benefits of following best practices and the potential consequences of not following these guidelines.",
        "previewLink": "No preview link",
        "isbn_13": "9781452281049",
        "original_path": "https://aibookshub.github.io/b1442/1442/Data Cleaning Guidelines.pdf"
    },
    {
        "id": "1442",
        "name": "Data Cleaning",
        "title": "Best Practices in Data Cleaning",
        "cover": "http://books.google.com/books/content?id=G8V1AwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "SAGE Publications",
        "author": "Jason W. Osborne",
        "summary": "Many researchers jump from data collection directly into testing hypothesis without realizing these tests can go profoundly wrong without clean data. This book provides a clear, accessible, step-by-step process of important best practices in preparing for data collection, testing assumptions, and examining and cleaning data in order to decrease error rates and increase both the power and replicability of results. Jason W. Osborne, author of the handbook Best Practices in Quantitative Methods (SAGE, 2008) provides easily-implemented suggestions that are evidence-based and will motivate change in practice by empirically demonstrating—for each topic—the benefits of following best practices and the potential consequences of not following these guidelines.",
        "previewLink": "No preview link",
        "isbn_13": "9781452281049",
        "original_path": "https://aibookshub.github.io/b1442/1442/Data Cleaning.pdf"
    },
    {
        "id": "1442",
        "name": "Data_Science_Interview_Prep_for_SQL,_Panda,_Python",
        "title": "Build a Career in Data Science",
        "cover": "http://books.google.com/books/content?id=4dDVDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Manning",
        "author": "Emily Robinson",
        "summary": "Summary You are going to need more than technical knowledge to succeed as a data scientist. Build a Career in Data Science teaches you what school leaves out, from how to land your first job to the lifecycle of a data science project, and even how to become a manager. Purchase of the print book includes a free eBook in PDF, Kindle, and ePub formats from Manning Publications. About the technology What are the keys to a data scientist’s long-term success? Blending your technical know-how with the right “soft skills” turns out to be a central ingredient of a rewarding career. About the book Build a Career in Data Science is your guide to landing your first data science job and developing into a valued senior employee. By following clear and simple instructions, you’ll learn to craft an amazing resume and ace your interviews. In this demanding, rapidly changing field, it can be challenging to keep projects on track, adapt to company needs, and manage tricky stakeholders. You’ll love the in",
        "previewLink": "No preview link",
        "isbn_13": "9781617296246",
        "original_path": "https://aibookshub.github.io/b1442/1442/Data_Science_Interview_Prep_for_SQL,_Panda,_Python.pdf"
    },
    {
        "id": "1442",
        "name": "Elements of Programming Interviews",
        "title": "Elements of Programming Interviews",
        "cover": "http://books.google.com/books/content?id=y6FLBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "EPI",
        "author": "Adnan Aziz",
        "summary": "The core of EPI is a collection of over 300 problems with detailed solutions, including 100 figures, 250 tested programs, and 150 variants. The problems are representative of questions asked at the leading software companies. The book begins with a summary of the nontechnical aspects of interviewing, such as common mistakes, strategies for a great interview, perspectives from the other side of the table, tips on negotiating the best offer, and a guide to the best ways to use EPI. The technical core of EPI is a sequence of chapters on basic and advanced data structures, searching, sorting, broad algorithmic principles, concurrency, and system design. Each chapter consists of a brief review, followed by a broad and thought-provoking series of problems. We include a summary of data structure, algorithm, and problem solving patterns.",
        "previewLink": "No preview link",
        "isbn_13": "9781479274833",
        "original_path": "https://aibookshub.github.io/b1442/1442/Elements of Programming Interviews.pdf"
    },
    {
        "id": "1442",
        "name": "Exercises for Programmers_ 57 Challenges to Develop Your Coding Skills 2015",
        "title": "Exercises for Programmers",
        "cover": "http://books.google.com/books/content?id=4sUNswEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "None",
        "author": "Brian P. Hogan",
        "summary": "One of the best ways to learn a programming language is to use it to solve problems. That's what this book is all about. Instead of questions rooted in theory, this book presents problems you'll encounter in everyday software development. Get sharp and stay sharp with more than fifty practice exercises rooted in real-world scenarios.",
        "previewLink": "No preview link",
        "isbn_13": "9781680501223",
        "original_path": "https://aibookshub.github.io/b1442/1442/Exercises for Programmers_ 57 Challenges to Develop Your Coding Skills 2015.pdf"
    },
    {
        "id": "1442",
        "name": "Interview Experience",
        "title": "301 Smart Answers to Tough Interview Questions",
        "cover": "http://books.google.com/books/content?id=qBDH76tl5-YC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Sourcebooks, Inc.",
        "author": "Vicky Oliver",
        "summary": "Packed full of the toughest interview questions and the savvy answers today's managers are looking for, this is the definitive guide to landing a job.",
        "previewLink": "No preview link",
        "isbn_13": "9781402203855",
        "original_path": "https://aibookshub.github.io/b1442/1442/Interview Experience.pdf"
    },
    {
        "id": "1442",
        "name": "Land the Tech Job You Love",
        "title": "Land the Tech Job You Love",
        "cover": "http://books.google.com/books/content?id=32bZPAAACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "Pragmatic Life",
        "author": "Andy Lester",
        "summary": "This title shows you how to make and maintain the connections that will drive your future career moves. It pulls no punches and lays out the details for what gets you an interview, and gets you hired in a job in the technical world that makes you happy.",
        "previewLink": "No preview link",
        "isbn_13": "9781934356265",
        "original_path": "https://aibookshub.github.io/b1442/1442/Land the Tech Job You Love.pdf"
    },
    {
        "id": "1442",
        "name": "LetMeRead.net__Routledge.Exercises.in.Programming.Style.2nd.Edition.0367350203",
        "title": "LetMeRead.net__Routledge.Exercises.in.Programming.Style.2nd.Edition.0367350203",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "Unknown publisher",
        "author": "Unknown Author",
        "summary": "No summary available",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1442/1442/LetMeRead.net__Routledge.Exercises.in.Programming.Style.2nd.Edition.0367350203.pdf"
    },
    {
        "id": "1442",
        "name": "Pandas Exercises for Data Analysis",
        "title": "Pandas Workout",
        "cover": "http://books.google.com/books/content?id=8GcFEQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Simon and Schuster",
        "author": "Reuven Lerner",
        "summary": "DESCRIPTION Practice makes perfect pandas. Work out your pandas skills against dozens of real-world challenges, each carefully designed to build an intuitive knowledge of essential pandas tasks. In Pandas Workout, discover 50 exercises that will strengthen your pandas skills to a level of automatic fluency. You'll test yourself against common pandas challenges such as data cleaning, and explore real-world datasets such as New York Taxis, Kickstarter projects, and global tourist spending. Detailed explanations help guide your success and make your new skills stick. You'll even get a big boost to productivity, with tasks that used to mean a trip to StackOverflow now a natural part of your skillset.",
        "previewLink": "No preview link",
        "isbn_13": "9781617299728",
        "original_path": "https://aibookshub.github.io/b1442/1442/Pandas Exercises for Data Analysis.pdf"
    },
    {
        "id": "1442",
        "name": "Programming Interviews Exposed - Third Edition",
        "title": "Programming Interviews Exposed",
        "cover": "http://books.google.com/books/content?id=FQzczWtdm3gC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "John Mongan",
        "summary": "The pressure is on during the interview process but with the right preparation, you can walk away with your dream job. This classic book uncovers what interviews are really like at America's top software and computer companies and provides you with the tools to succeed in any situation. The authors take you step-by-step through new problems and complex brainteasers they were asked during recent technical interviews. 50 interview scenarios are presented along with in-depth analysis of the possible solutions. The problem-solving process is clearly illustrated so you'll be able to easily apply what you've learned during crunch time. You'll also find expert tips on what questions to ask, how to approach a problem, and how to recover if you become stuck. All of this will help you ace the interview and get the job you want. What you will learn from this book Tips for effectively completing the job application Ways to prepare for the entire programming interview process How to find the kind o",
        "previewLink": "No preview link",
        "isbn_13": "9781118169384",
        "original_path": "https://aibookshub.github.io/b1442/1442/Programming Interviews Exposed - Third Edition.pdf"
    },
    {
        "id": "1442",
        "name": "Programming_Interviews_Exposed_Coding_Your_Way_Through_the_Interview",
        "title": "Programming Interviews Exposed",
        "cover": "http://books.google.com/books/content?id=QKtTDwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "John Mongan",
        "summary": "Ace technical interviews with smart preparation Programming Interviews Exposed is the programmer’s ideal first choice for technical interview preparation. Updated to reflect changing techniques and trends, this new fourth edition provides insider guidance on the unique interview process that today's programmers face. Online coding contests are being used to screen candidate pools of thousands, take-home projects have become commonplace, and employers are even evaluating a candidate's public code repositories at GitHub—and with competition becoming increasingly fierce, programmers need to shape themselves into the ideal candidate well in advance of the interview. This book doesn't just give you a collection of questions and answers, it walks you through the process of coming up with the solution so you learn the skills and techniques to shine on whatever problems you’re given. This edition combines a thoroughly revised basis in classic questions involving fundamental data structures and",
        "previewLink": "No preview link",
        "isbn_13": "9781119418481",
        "original_path": "https://aibookshub.github.io/b1442/1442/Programming_Interviews_Exposed_Coding_Your_Way_Through_the_Interview.pdf"
    },
    {
        "id": "1442",
        "name": "Python For Data Analysis by Boston University",
        "title": "Python Data Analysis",
        "cover": "http://books.google.com/books/content?id=BqEbBQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "Packt Publishing Ltd",
        "author": "Ivan Idris",
        "summary": "This book is for programmers, scientists, and engineers who have knowledge of the Python language and know the basics of data science. It is for those who wish to learn different data analysis methods using Python and its libraries. This book contains all the basic ingredients you need to become an expert data analyst.",
        "previewLink": "No preview link",
        "isbn_13": "9781783553365",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python For Data Analysis by Boston University.pdf"
    },
    {
        "id": "1442",
        "name": "Python For Data Analysis Free EBook",
        "title": "Python Data Science Handbook",
        "cover": "http://books.google.com/books/content?id=6omNDQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "\"O'Reilly Media, Inc.\"",
        "author": "Jake VanderPlas",
        "summary": "For many researchers, Python is a first-class tool mainly because of its libraries for storing, manipulating, and gaining insight from data. Several resources exist for individual pieces of this data science stack, but only with the Python Data Science Handbook do you get them all—IPython, NumPy, Pandas, Matplotlib, Scikit-Learn, and other related tools. Working scientists and data crunchers familiar with reading and writing Python code will find this comprehensive desk reference ideal for tackling day-to-day issues: manipulating, transforming, and cleaning data; visualizing different types of data; and using data to build statistical or machine learning models. Quite simply, this is the must-have reference for scientific computing in Python. With this handbook, you’ll learn how to use: IPython and Jupyter: provide computational environments for data scientists using Python NumPy: includes the ndarray for efficient storage and manipulation of dense data arrays in Python Pandas: feature",
        "previewLink": "No preview link",
        "isbn_13": "9781491912133",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python For Data Analysis Free EBook.pdf"
    },
    {
        "id": "1442",
        "name": "Python for Data Analysis",
        "title": "Python for Data Analysis",
        "cover": "http://books.google.com/books/content?id=UiM3DwAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "\"O'Reilly Media, Inc.\"",
        "author": "Wes McKinney",
        "summary": "Get complete instructions for manipulating, processing, cleaning, and crunching datasets in Python. Updated for Python 3.6, the second edition of this hands-on guide is packed with practical case studies that show you how to solve a broad set of data analysis problems effectively. You’ll learn the latest versions of pandas, NumPy, IPython, and Jupyter in the process. Written by Wes McKinney, the creator of the Python pandas project, this book is a practical, modern introduction to data science tools in Python. It’s ideal for analysts new to Python and for Python programmers new to data science and scientific computing. Data files and related material are available on GitHub. Use the IPython shell and Jupyter notebook for exploratory computing Learn basic and advanced features in NumPy (Numerical Python) Get started with data analysis tools in the pandas library Use flexible tools to load, clean, transform, merge, and reshape data Create informative visualizations with matplotlib Apply ",
        "previewLink": "No preview link",
        "isbn_13": "9781491957615",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python for Data Analysis.pdf"
    },
    {
        "id": "1442",
        "name": "python面试宝典",
        "title": "程序员面试宝典",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "欧立奇",
        "summary": "本书是《程序员面试宝典》的第二版,在保留第一版的数据结构、面向对象、程序设计等主干的基础上,使用各大IT公司及相关企业2007~2008年的最新面试题替换和补充原内容,以反映自第一版以来近2年的时间所发生的变化。",
        "previewLink": "No preview link",
        "isbn_13": "9787121073793",
        "original_path": "https://aibookshub.github.io/b1442/1442/python面试宝典.pdf"
    },
    {
        "id": "1442",
        "name": "Python面试通关宝典",
        "title": "Python面试通关宝典",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "洪锦魁",
        "summary": "本书内容分为两篇,第1篇是Python语言面试题,第2篇是算法面试题.Python语言面试题涵盖面试通用问题,Python语法面试题,函数,类,模块,文件管理,正则表达式以及Python语言综合应用;算法面试题涵盖排序,搜寻,字符串,数组,链表,二叉树,堆栈,数学问题,贪婪算法,动态规划算法以及综合应用.本书包括100多个问答题和300多个程序实例,帮助读者快速掌握Python语法与算法的知识.",
        "previewLink": "No preview link",
        "isbn_13": "9787302565017",
        "original_path": "https://aibookshub.github.io/b1442/1442/Python面试通关宝典.pdf"
    },
    {
        "id": "1442",
        "name": "SQL Notes for Professionals",
        "title": "PHP Notes for Professionals",
        "cover": "http://books.google.com/books/content?id=fwU6EQAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "EduGorilla Publication",
        "author": "Mr. Rohit Manglik",
        "summary": "EduGorilla Publication is a trusted name in the education sector, committed to empowering learners with high-quality study materials and resources. Specializing in competitive exams and academic support, EduGorilla provides comprehensive and well-structured content tailored to meet the needs of students across various streams and levels.",
        "previewLink": "No preview link",
        "isbn_13": "9789367849286",
        "original_path": "https://aibookshub.github.io/b1442/1442/SQL Notes for Professionals.pdf"
    },
    {
        "id": "1442",
        "name": "The Google Resume",
        "title": "The Google Resume",
        "cover": "http://books.google.com/books/content?id=yQ3VngEACAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "John Wiley & Sons",
        "author": "Gayle Laakmann McDowell",
        "summary": "Describes how to land the job of one's dreams at a top tech company through choosing the correct major and extra-curricular activities in college, what other experiences appeal to employers and how to design and tailor one's resume.",
        "previewLink": "No preview link",
        "isbn_13": "9780470927625",
        "original_path": "https://aibookshub.github.io/b1442/1442/The Google Resume.pdf"
    },
    {
        "id": "1442",
        "name": "The_Self_Taught_Programmer_The_Definitive_Guide",
        "title": "The Self-taught Programmer",
        "cover": "http://books.google.com/books/content?id=iZ4wEAAAQBAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "Hachette UK",
        "author": "Cory Althoff",
        "summary": "'One of the best software design books of all time' - BookAuthority Cory Althoff is a self-taught programmer. After a year of self-study, he learned to program well enough to land a job as a software engineer II at eBay. But once he got there, he realised he was severely under-prepared. He was overwhelmed by the amount of things he needed to know but hadn't learned. His journey learning to program, and his experience in first software engineering job were the inspiration for this book. This book is not just about learning to program, although you will learn to code. If you want to program professionally, it is not enough to learn to code; that is why, in addition to helping you learn to program, Althoff also cover the rest of the things you need to know to program professionally that classes and books don't teach you. The Self-taught Programmer is a roadmap, a guide to take you from writing your first Python program to passing your first technical interview. The book is divided into fi",
        "previewLink": "No preview link",
        "isbn_13": "9781472147097",
        "original_path": "https://aibookshub.github.io/b1442/1442/The_Self_Taught_Programmer_The_Definitive_Guide.pdf"
    },
    {
        "id": "1442",
        "name": "剑指offer - 名企面试官精讲典型编程题",
        "title": "剑指Offer",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "何海涛 (软件工程师)",
        "summary": "本书剖析了80个典型的编程面试题,系统整理基础知识,代码质量,解题思路,优化效率和综合能力这5个面试要点.",
        "previewLink": "No preview link",
        "isbn_13": "9787121310928",
        "original_path": "https://aibookshub.github.io/b1442/1442/剑指offer - 名企面试官精讲典型编程题.pdf"
    },
    {
        "id": "1442",
        "name": "教你如何迅速秒杀掉：99%的海量数据处理面试题",
        "title": "教師專業發展",
        "cover": "http://books.google.com/books/content?id=G-P_CgAAQBAJ&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api",
        "publisher": "高等教育文化事業有限公司",
        "author": "高等教育出版",
        "summary": "應用「教學圈」支持教師專業發展的策略／黃旭鈞 國民小學推廣行動學習之關切階層研究／王令宜、高熏芳 歷史教師應具備的教學專業素養／單文經 蘇格蘭教學總會推動教師專業發展之歷史探究，1966／林仁傑 高職專業群科教師專業標準內涵之探究：以學校實務工作者觀點分析／許宛琪、胡茹萍 中國大陸教師專業標準及其應用分析／吳清基、邱于真 探思教師專業標準之發展與運用／潘慧玲 教師專業標準應用於教師評鑑之實務議題初探／甄曉蘭 杜威學習共同體的理念闡釋／單文經 教育專業發展的潛在危機與理想藍圖／林志成",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1442/1442/教你如何迅速秒杀掉：99%的海量数据处理面试题.pdf"
    },
    {
        "id": "1442",
        "name": "编程之法：面试和算法心得",
        "title": "编程之法",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "July",
        "summary": "Ben shu she ji mian shi,Suan fa,Ji qi xue xi san ge zhu ti.Shu zhong de mei dao bian cheng ti mu dou ji chu le duo zhong si lu,Duo zhong jie fa,Bu duan you hua,Zhu ceng di jin.Quan shu gong 7 zhang,Di 1 zhang zhi di 6 zhang fen bie chan shu zi fu chuan,Shu zu,Shu,Cha zhao,Dong tai gui hua,Hai liang shu ju chu li deng xiang guan de bian cheng mian shi ti he suan fa;Di 7 zhang jie shao ji qi xue xi de liang ge suan faK jin lin he SVM.",
        "previewLink": "No preview link",
        "isbn_13": "9787115381613",
        "original_path": "https://aibookshub.github.io/b1442/1442/编程之法：面试和算法心得.pdf"
    },
    {
        "id": "1442",
        "name": "编程之美—微软技术面试心得《编程之美》小组",
        "title": "出版人",
        "cover": "http://books.google.com/books/content?id=c9dMAQAAIAAJ&printsec=frontcover&img=1&zoom=5&source=gbs_api",
        "publisher": "None",
        "author": "Unknown Author",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "",
        "original_path": "https://aibookshub.github.io/b1442/1442/编程之美—微软技术面试心得《编程之美》小组.pdf"
    },
    {
        "id": "1442",
        "name": "金领简历 - 敲开苹果、微软、谷歌的大门",
        "title": "金领简历",
        "cover": "https://raw.githubusercontent.com/aibookshub/aibookshub/main/assets/images/covermissing.png",
        "publisher": "None",
        "author": "漆犇",
        "summary": "None",
        "previewLink": "No preview link",
        "isbn_13": "9787115279262",
        "original_path": "https://aibookshub.github.io/b1442/1442/金领简历 - 敲开苹果、微软、谷歌的大门.pdf"
    }
];
